export const users = [
  {
    name: 'Fleet Manager',
    email: 'admin@transitops.com',
    password: 'admin123',
    role: 'Fleet Manager',
    phone: '+91-9876543210',
    isActive: true,
  },
  {
    name: 'Priya Sharma',
    email: 'safety@transitops.com',
    password: 'safety123',
    role: 'Safety Officer',
    phone: '+91-9876543211',
    isActive: true,
  },
  {
    name: 'Amit Patel',
    email: 'driver@transitops.com',
    password: 'driver123',
    role: 'Driver',
    phone: '+91-9876543212',
    isActive: true,
  },
  {
    name: 'Sneha Reddy',
    email: 'finance@transitops.com',
    password: 'finance123',
    role: 'Financial Analyst',
    phone: '+91-9876543213',
    isActive: true,
  },
  {
    name: 'Vikram Singh',
    email: 'driver2@transitops.com',
    password: 'driver123',
    role: 'Driver',
    phone: '+91-9876543214',
    isActive: true,
  },
  {
    name: 'Ananya Gupta',
    email: 'manager@transitops.com',
    password: 'manager123',
    role: 'Fleet Manager',
    phone: '+91-9876543215',
    isActive: true,
  },
];
