export const vehicles = [
  {
    regNumber: 'MH-01-AB-1234',
    name: 'City Express 1',
    type: 'Bus',
    maxLoadCapacity: 50,
    odometer: 125340,
    acquisitionCost: 3500000,
    status: 'Available',
    region: 'Mumbai',
  },
  {
    regNumber: 'MH-01-CD-5678',
    name: 'Metro Shuttle A',
    type: 'Mini Bus',
    maxLoadCapacity: 25,
    odometer: 87200,
    acquisitionCost: 1800000,
    status: 'On Trip',
    region: 'Mumbai',
  },
  {
    regNumber: 'DL-02-EF-9012',
    name: 'Capital Liner 3',
    type: 'Bus',
    maxLoadCapacity: 55,
    odometer: 210500,
    acquisitionCost: 4200000,
    status: 'Available',
    region: 'Delhi',
  },
  {
    regNumber: 'KA-03-GH-3456',
    name: 'Tech Park Shuttle',
    type: 'Van',
    maxLoadCapacity: 12,
    odometer: 45600,
    acquisitionCost: 1200000,
    status: 'On Trip',
    region: 'Bangalore',
  },
  {
    regNumber: 'TN-04-IJ-7890',
    name: 'Chennai Express 2',
    type: 'Bus',
    maxLoadCapacity: 48,
    odometer: 156800,
    acquisitionCost: 3200000,
    status: 'In Shop',
    region: 'Chennai',
  },
  {
    regNumber: 'MH-01-KL-2345',
    name: 'Harbor Line Van',
    type: 'Van',
    maxLoadCapacity: 10,
    odometer: 32100,
    acquisitionCost: 950000,
    status: 'Available',
    region: 'Mumbai',
  },
  {
    regNumber: 'DL-02-MN-6789',
    name: 'Green Line Bus',
    type: 'Electric Bus',
    maxLoadCapacity: 40,
    odometer: 18500,
    acquisitionCost: 5500000,
    status: 'Available',
    region: 'Delhi',
  },
  {
    regNumber: 'KA-03-OP-1234',
    name: 'Airport Connector',
    type: 'Mini Bus',
    maxLoadCapacity: 30,
    odometer: 67800,
    acquisitionCost: 2100000,
    status: 'On Trip',
    region: 'Bangalore',
  },
  {
    regNumber: 'GJ-05-QR-5678',
    name: 'Ahmedabad City Bus',
    type: 'Bus',
    maxLoadCapacity: 52,
    odometer: 198400,
    acquisitionCost: 3000000,
    status: 'Available',
    region: 'Ahmedabad',
  },
  {
    regNumber: 'RJ-06-ST-9012',
    name: 'Pink City Shuttle',
    type: 'Mini Bus',
    maxLoadCapacity: 20,
    odometer: 54300,
    acquisitionCost: 1500000,
    status: 'Available',
    region: 'Jaipur',
  },
  {
    regNumber: 'TN-04-UV-3456',
    name: 'Coromandel Van',
    type: 'Van',
    maxLoadCapacity: 8,
    odometer: 28700,
    acquisitionCost: 800000,
    status: 'Retired',
    region: 'Chennai',
  },
  {
    regNumber: 'MH-01-WX-7890',
    name: 'Western Express 4',
    type: 'Bus',
    maxLoadCapacity: 50,
    odometer: 142000,
    acquisitionCost: 3600000,
    status: 'Available',
    region: 'Mumbai',
  },
];
